# Generated by Django 4.0 on 2021-12-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koi', '0002_alter_category_id_alter_dapanes_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='koinoxrista',
            name='url',
            field=models.URLField(default='#', verbose_name='Αρχεία'),
        ),
    ]
